version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_SECRET}
        databases:
          default:
            connector: mysql
            host: test.com
            user: testid
            password: testpassword
            rawAccess: true
            port: '3306'
            migrations: true
